version: '3.6'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/doc-manager-web
      - sqlite_data:/app/doc-manager-web/data
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - SQL_ENGINE=django.db.backends.sqlite3
      - DATABASE=db.sqlite3
    
volumes:
  sqlite_data:
