version: '4'

services:
  web:
    build:
      context: ../FYP_backend
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 10.121.4.110:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: sqlite:latest
    volumes:
      - sqlite_data:/var/lib/sqlite/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  sqlite_data:
  static_volume:
  media_volume: