# Generated by Django 4.0.3 on 2024-03-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.department'),
        ),
    ]
