# Generated by Django 4.0.3 on 2024-04-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0003_alter_triprequest_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='code',
        ),
    ]
