# Generated by Django 4.0.3 on 2024-04-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0004_remove_triprequest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='active', max_length=10),
        ),
    ]
