# Generated by Django 5.0.4 on 2024-05-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='able_to_book',
        ),
        migrations.AddField(
            model_name='schedule',
            name='able_to_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationApp.department'),
        ),
    ]
