# Generated by Django 5.0.4 on 2024-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0011_remove_schedule_able_to_book_schedule_able_to_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='able_to_book',
        ),
        migrations.AddField(
            model_name='schedule',
            name='able_to_book',
            field=models.ManyToManyField(related_name='bookable_trips', to='reservationApp.department'),
        ),
    ]
