# Generated by Django 5.0.4 on 2024-05-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0014_userprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
