# Generated by Django 5.0.4 on 2024-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0017_alter_triprequest_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='seats_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
