# Generated by Django 5.0.4 on 2024-05-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0018_triprequest_description_triprequest_seats_needed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triprequest',
            old_name='fare',
            new_name='seats',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='seats_needed',
        ),
    ]
