# Generated by Django 5.0.4 on 2024-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0019_rename_fare_triprequest_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='fare',
        ),
        migrations.AddField(
            model_name='schedule',
            name='seats_available',
            field=models.IntegerField(null=True),
        ),
    ]
