# Generated by Django 5.0.4 on 2024-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0020_remove_schedule_fare_schedule_seats_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='able_to_book',
            field=models.CharField(choices=[('None', 'None'), ('Student', 'Student'), ('Staff', 'Staff'), ('Faculty', 'Faculty')], default='None', max_length=10),
        ),
    ]
