# Generated by Django 5.0.4 on 2024-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0024_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
