# Generated by Django 5.0.4 on 2024-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0025_triprequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
