# Generated by Django 4.0.3 on 2024-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car_type',
            field=models.CharField(choices=[(4, 'Small Car'), (28, 'Bus')], max_length=50),
        ),
    ]
